Estilos del layout
cetav-ddw/hogarexcelencia pull request #2
Opened 2017-03-13 19:04 UTC by iirenesg

2017-03-14 01:58 UTC, jleiva requested changes

2017-03-14 01:58 UTC, jleiva commented on sites/all/themes/hogar/layouts/hogarpage/hogarpage.tpl.php
> +      <div class="clearfix">
nelpastel, esto es innecesario

2017-03-14 01:58 UTC, jleiva commented on sites/all/themes/hogar/sass/partials/elements/_images.scss
> +  margin: 24px 0;
todas las imagenes del sitio necesitan este margin?

2017-03-14 01:58 UTC, jleiva commented on sites/all/themes/hogar/sass/partials/layout/_main.scss
> +		display: inline-block;
agrega el screen and, o usa el mixin porfa

2017-03-14 01:58 UTC, jleiva commented on sites/all/themes/hogar/sass/partials/modules/_photo-module.scss
> +.photo-module-container .view-content {
y el fallback para esto?

2017-03-14 01:58 UTC, jleiva commented on sites/all/themes/hogar/sass/partials/utilitary/_misc.scss
> +.admin-menu-icon {
hay un folder con partials para overwrites de cosas especificas de Drupal, movelo ahi porfa

2017-03-14 18:18 UTC, iirenesg commented on sites/all/themes/hogar/sass/partials/utilitary/_misc.scss
> +.admin-menu-icon {
El folder de overwrites de cosas de drupal se renderiza antes que los estilos que están afectando ese ícono, si lo muevo ahí no va a tener ningún efecto. Puedo cambiar el orden de renderización en el sass principal, esa sería una solución.

2017-03-14 18:20 UTC, iirenesg commented on sites/all/themes/hogar/sass/partials/elements/_images.scss
> +  margin: 24px 0;
Ese margen es pensando en estilos base para imágenes que en un futuro incluya otro usuario, así no se pega con el texto ni arriba ni abajo. En realidad ninguna imagen del tema lo ocupa.

2017-03-14 18:21 UTC, iirenesg commented on sites/all/themes/hogar/layouts/hogarpage/hogarpage.tpl.php
> +      <div class="clearfix">
Voy a intentar buscar otras soluciones, pero para el título a la izquierda y el texto a la derecha nada más funcionó.

2017-03-14 19:04 UTC, jleiva commented on sites/all/themes/hogar/sass/partials/elements/_images.scss
> +  margin: 24px 0;
mejor quitarlo, y solo asegurarse que elementos como p, ul y h's si tengan el margin

2017-03-14 19:05 UTC, jleiva commented on sites/all/themes/hogar/sass/partials/utilitary/_misc.scss
> +.admin-menu-icon {
ok, dejalo

2017-03-14 19:06 UTC, jleiva commented on sites/all/themes/hogar/css/style.css
>    list-style-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAALCAYAAABLcGxfAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAJNJREFUeNpi+P//PwMSFgDiLCA2QBOHY2SOAxB/+A8BIPoaEC+AGoKh
para los proximos, no agregar el css compilado ni el map

2017-03-14 19:06 UTC, jleiva commented on sites/all/themes/hogar/layouts/hogarpage/hogarpage.tpl.php
> +      <div class="clearfix">
ok

2017-03-16 16:18 UTC, jleiva approved these changes
Revisa los comentarios, si tenes preguntas me avisas. Yo voy a aplicar los cambios que te puse.

2017-03-16 16:18 UTC, jleiva commented on sites/all/themes/hogar/sass/style.scss
> +@import "partials/third-party/typebase";
porque fue necesario moverlo aca?

2017-03-16 16:18 UTC, jleiva commented on sites/all/themes/hogar/sass/partials/third-party/_typebase.scss
> +    font-size: $baseFontSize / 15 * 90%;
porque 15? 16 es como el default font size en los browsers, por eso lo usan, no es un numero magico

2017-03-16 16:18 UTC, jleiva commented on sites/all/themes/hogar/sass/partials/modules/_photo-module.scss
> +.photo-module-container {
Voy a ir cambiando el nombre de clases, usando BEM. Leete esto http://getbem.com/naming/ si hay preguntas me avisas

2017-03-16 16:18 UTC, jleiva commented on sites/all/themes/hogar/sass/partials/modules/_cta.scss
>  	.float-left {
no es buena idea usar este tipo de clases utilitarias, da mas trabajo tener que ponerlo en el HTML cada vez que se necesite

2017-03-16 16:18 UTC, jleiva commented on sites/all/themes/hogar/sass/partials/layout/_main.scss
> +.left-column {
este nombre pense que ya habiamos quedado en usar algo mas descriptivo

2017-03-16 16:18 UTC, jleiva commented on sites/all/themes/hogar/layouts/hogarpage/hogarpage.tpl.php
> +              <?php print $content['left']; ?>
pense que habiamos acordado usar nombres mas descriptivos para las regiones y para el nombre de la clase, de todas maneras lo voy a cambiar.

2017-03-16 16:20 UTC, merged